---
version: '3.6'

services:
  hasura:
    build: ./hasura
    depends_on:
      - database
    environment:
      PORT: ${HASURA_PORT}
      DATABASE_URL: ${DATABASE_URL}

  database:
    image: postgres:12
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  database:
...
